theme: jekyll-theme-minimal
title: jstdrmabtit´s page
description: This shows when the website index file is deleted or git hub cant show it. so please be patient. Meanwhile you can pay a visit to this project´s repository here!: https://github.com/jstdrmabtit/jstdrmabtit.github.io/blob/main/_config.yml
Have Fun Waiting lol.
